# Generated by Django 4.0.4 on 2022-05-28 21:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MdBot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('token', models.CharField(max_length=200)),
                ('social', models.CharField(choices=[('TG', 'Telegram'), ('IN', 'Instagram'), ('VK', 'Vkontakte'), ('FB', 'Facebook'), ('DC', 'Discord')], max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='MdBotChat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('chat_id', models.IntegerField()),
                ('public', models.BooleanField(default=False)),
                ('bot', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.mdbot')),
            ],
        ),
        migrations.CreateModel(
            name='MdChatUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('social_id', models.IntegerField()),
                ('username', models.CharField(max_length=50)),
                ('lang_code', models.CharField(max_length=50, null=True)),
                ('waiting', models.CharField(max_length=50, null=True)),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.mdbotchat')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MdBotRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.IntegerField(choices=[(1, 'Emcd'), (2, 'Currency')])),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.mdbotchat')),
            ],
        ),
    ]
